name: ci-linux
on:
  pull_request:
  push:
    paths:
      - '.github/workflows/ci-linux.yaml'
      - 'cabal.project'
      - '*/src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v17
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            substituters = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            allow-import-from-derivation = true
      - name: nix build
        run: nix build .
